language: c
sudo: false

script: echo "Commit $TRAVIS_COMMIT" > build-product.txt

before_deploy: bash ./ci-deploy.sh

deploy:
  # Deploy tagged releases to GitHub
  - provider: releases
    api_key: $GITHUB_API_KEY
    file: "artifacts/deploytest-$TRAVIS_TAG.txt"
    skip_cleanup: true
    on:
      repo: fhunleth/deploytest
      tags: true
  # Copy all build products to S3
  - provider: s3
    access_key_id: $ARTIFACTS_KEY
    secret_access_key: $ARTIFACTS_SECRET
    bucket: $ARTIFACTS_BUCKET
    skip_cleanup: true
    local_dir: artifacts
    upload-dir: nerves-sdk
    storage_class: "REDUCED_REDUNDANCY"  # doesn't work yet
    on:
      repo: fhunleth/deploytest
      all_branches: true
